### ISSUE TITLE
No mouse in dispmanx fullscreen rpi64

### ISSUE THREAD

**Issue by br6** [midwan/amiberry#615]
I make the rpi64 build with dispmanx support (manjaro arm 20.0x rpi4 4gb) keyboard works but not mouse.

I have the following in my config.txt

e /boot/overlays/README for all available options 
gpu_mem=256 
initramfs initramfs-linux.img followkernel 
kernel=kernel8.img 
arm_64bit=1 
enable_gic=1 
disable_overscan=1
#enable sound
dtparam=audio=on 
hdmi_force_hotplug=1 
hdmi_drive=2 
hdmi_group=2 
hdmi_mode=82
#enable vc4
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

I used the below wiki for dispmanx support (64bit supported now on rpi4)

https://github.com/midwan/amiberry/wiki/Compile-for-Raspberry-Pi-64bit

**Comment by br6** [comment]
Im getting this now when running make. 
ce/vcos/pthreads  -DFASTERCYCLES -I/usr/include/SDL2 -D_REENTRANT -Iexternal/libguisan/include -Isrc -Isrc/osdep -Isrc/threaddep -Isrc/include -Isrc/archivers -I/usr/include/libxml2 -DAMIBERRY  -c -o src/inputdevice.o src/inputdevice.cpp
In file included from src/inputdevice.cpp:39:
src/osdep/amiberry_gfx.h:5:10: fatal error: bcm_host.h: No such file or directory
    5 | #include <bcm_host.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/inputdevice.o] Error 1

**Comment by solskogen** [comment]
My guess is that you didn't really install the rpi-userland.
Do you have /opt/vc/include?

**Comment by midwan** [comment]
@br6 
Like @solskogen said, it looks like you're missing the rpi-userland, otherwise the missing header should be there. Please check your installation again, perhaps something went wrong and you didn't notice that it failed?

**Comment by br6** [comment]
The failed build was on a fresh git pull.
I will have another go and update back

**Comment by br6** [comment]
Update, i have tried again , its completed the build from git but still no mouse in fullscreen.

**Comment by midwan** [comment]
@br6 
Are you sure you're using the `fkms` driver in `/boot/config.txt` ? That's the only scenario where I've see the mouse pointer missing (`fkms` not being used).

**Comment by br6** [comment]
I have posted my config further up,
Im going to install again on another pi with manajaro (pinn version)
Will let you know

**Comment by br6** [comment]
> I have posted my config further up, this is present dtoverlay=vc4-fkms-v3d
> Im going to install again on another pi with Manjaro (pinn version)
> Will let you know

Ive tried on another pi4 same manjaro 20.04 userland git cloned (todays code) same issue keyboard works but no mouse cursor.

**Comment by solskogen** [comment]
Does you mouse work in X11?

**Comment by br6** [comment]
> Does you mouse work in X11?

Yes you mean in windowed mode ?

**Comment by solskogen** [comment]
I mean in X11 / X. As in when you run Lightdm and XFCE. 
I noticed that with the latest kernel, the mouse cursor looks like garbage. Does something semi-transparent move around when you move the mouse?

**Comment by br6** [comment]
> I mean in X11 / X. As in when you run Lightdm and XFCE.
> I noticed that with the latest kernel, the mouse cursor looks like garbage. Does something semi-transparent move around when you move the mouse?

Yes mouse cursor shows in the gui in desktop xfce.

**Comment by br6** [comment]
Ive tried again with a lower kernel 4.19 on Manjaro 20.04 KDE,
the cursor loads in dispmanx build but its quits when I start . Is there a way to launch with logging or debug mode

**Comment by midwan** [comment]
You can enable logging by editing the file conf/amiberry.conf and setting the `write_logfile` option to `yes`.

If you want a debug build, you'll have to edit the Makefile and set DEBUG to 1 instead.

**Comment by midwan** [comment]
Closing this due to inactivity - The dispmanx version on 64-bit is experimental anyway, and not officially supported by any distro maintainer. It might work at some point, break with an update, etc.
